// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceQuality.Infrastructure.Data;

#nullable disable

namespace ServiceQuality.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507043136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServiceQuality.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@atlink.asia",
                            FullName = "Super Administrator",
                            IsActive = true,
                            Password = "$2a$11$xJ3Y9z8K.mNpQ2vR7wL4guHdE5fT1oUiA6kC9bX0nWsM3qDrPyZeO",
                            Role = "SuperAdmin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("AppConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfigKey = "welcome_title",
                            ConfigValue = "Đánh Giá Chất Lượng Dịch Vụ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiêu đề màn hình chào"
                        },
                        new
                        {
                            Id = 2,
                            ConfigKey = "welcome_subtitle",
                            ConfigValue = "Xin chào! Hãy chia sẻ trải nghiệm của bạn với chúng tôi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phụ đề màn hình chào"
                        },
                        new
                        {
                            Id = 3,
                            ConfigKey = "thankyou_message",
                            ConfigValue = "Cảm ơn bạn đã đánh giá! Chúng tôi sẽ cải thiện dịch vụ tốt hơn.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thông điệp cảm ơn"
                        },
                        new
                        {
                            Id = 4,
                            ConfigKey = "reset_timeout_seconds",
                            ConfigValue = "10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thời gian tự reset app về màn hình chào (giây)"
                        },
                        new
                        {
                            Id = 5,
                            ConfigKey = "primary_color",
                            ConfigValue = "#1976D2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màu chủ đạo của app"
                        });
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CommentLabel")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("CommentRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("MinScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DisplayOrder", "IsActive");

                    b.ToTable("EvaluationCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowComment = true,
                            CommentLabel = "Bạn muốn chia sẻ thêm điều gì?",
                            CommentRequired = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Nhân viên có thân thiện và nhiệt tình phục vụ?",
                            DisplayOrder = 1,
                            Icon = "👤",
                            IsActive = true,
                            IsRequired = true,
                            MaxScore = 5,
                            MinScore = 1,
                            Name = "Thái độ nhân viên"
                        },
                        new
                        {
                            Id = 2,
                            AllowComment = true,
                            CommentLabel = "Sản phẩm bạn sử dụng hôm nay là gì?",
                            CommentRequired = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Sản phẩm có đạt chất lượng như kỳ vọng của bạn?",
                            DisplayOrder = 2,
                            Icon = "⭐",
                            IsActive = true,
                            IsRequired = true,
                            MaxScore = 5,
                            MinScore = 1,
                            Name = "Chất lượng sản phẩm"
                        },
                        new
                        {
                            Id = 3,
                            AllowComment = false,
                            CommentRequired = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Không gian cửa hàng có sạch sẽ và thoải mái?",
                            DisplayOrder = 3,
                            Icon = "🏬",
                            IsActive = true,
                            IsRequired = true,
                            MaxScore = 5,
                            MinScore = 1,
                            Name = "Không gian & Môi trường"
                        });
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Score");

                    b.HasIndex("SessionId");

                    b.ToTable("EvaluationItems", (string)null);
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ConfigSnapshot")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DevicePlatform")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.HasIndex("SubmittedAt");

                    b.ToTable("EvaluationSessions", (string)null);
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationCategory", b =>
                {
                    b.HasOne("ServiceQuality.Domain.Entities.AdminUser", "Creator")
                        .WithMany("CreatedCategories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationItem", b =>
                {
                    b.HasOne("ServiceQuality.Domain.Entities.EvaluationCategory", "Category")
                        .WithMany("EvaluationItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceQuality.Domain.Entities.EvaluationSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("CreatedCategories");
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationCategory", b =>
                {
                    b.Navigation("EvaluationItems");
                });

            modelBuilder.Entity("ServiceQuality.Domain.Entities.EvaluationSession", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
